# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-25 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('publisher', models.CharField(max_length=100)),
                ('isbn', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('published_date', models.DateTimeField(blank=True)),
                ('quantity', models.IntegerField(default=0)),
                ('image_name', models.TextField()),
            ],
        ),
    ]
