# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-26 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20151225_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='published_date',
        ),
        migrations.AddField(
            model_name='book',
            name='published_year',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
