# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20151225_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(default='fantasy', max_length=50),
        ),
    ]
